---
- name: Disable PostgreSQL AppStream module
  become: true
  ansible.builtin.command: dnf -y module disable postgresql
  register: _pgsql_disable_module
  changed_when: >-
    'Disabling modules:' in _pgsql_disable_module.stdout

- name: Install official PostgreSQL repository
  become: true
  ansible.builtin.dnf:
    name:
      - "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
    disable_gpg_check: true

- name: Install PostgreSQL packages
  become: true
  ansible.builtin.dnf:
    name:
      - python3-psycopg2
      - "postgresql{{ pgsql_major_version | string }}-server"
    state: present

- name: Install pgAudit package
  when:
    - pgsql_install_pgaudit
  become: true
  ansible.builtin.dnf:
    name:
      - "{{ _pgsql_pgaudit_package_name }}"
    state: present

- name: Install TimescaleDB
  when:
    - pgsql_install_timescaledb
  block:
    - name: Create TimescaleDB repository config file
      become: true
      ansible.builtin.yum_repository:
        name: timescale_timescaledb
        description: timescale_timescaledb
        baseurl:
          - "https://packagecloud.io/timescale/timescaledb/el/{{ ansible_distribution_major_version }}/$basearch"
        repo_gpgcheck: true
        gpgcheck: false
        enabled: true
        gpgkey:
          - https://packagecloud.io/timescale/timescaledb/gpgkey
        sslverify: true
        sslcacert: /etc/pki/tls/certs/ca-bundle.crt
        metadata_expire: 300
        state: present
        owner: root
        group: root
        mode: '0644'

    - name: Install TimescaleDB package
      become: true
      ansible.builtin.dnf:
        name:
          - "timescaledb-2-postgresql-{{ pgsql_major_version | string }}"
        state: present
        update_cache: true
