---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: vault
    box: jtarpley/rocky9_cis
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: postgresql_install_
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky9_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: postgresql_install_
    groups:
      - subjects
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        vault_token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        vault_url: "http://{{ hostvars['vault'].ansible_host }}:8200"
      subjects:
        pgsql_major_version: ${MOLECULE_PGSQL_MAJOR_VERSION:-17}
        pgsql_install_timescaledb: ${MOLECULE_INSTALL_TIMESCALEDB:-true}
        pgsql_ssl: true
        pgsql_ssl_ca_file: >-
          {{ '/etc/pki/ca-trust/source/anchors/ca_chain.crt' if ansible_os_family == 'RedHat' else '/usr/local/share/ca-certificates/ca_chain.crt' }}
        pgsql_ssl_cert_file: >-
          {{ '/etc/pki/tls/certs/server.crt' if ansible_os_family == 'RedHat' else '/etc/ssl/certs/server.crt' }}
        pgsql_ssl_key_file: >-
          {{ '/etc/pki/tls/private/server.key' if ansible_os_family == 'RedHat' else '/etc/ssl/private/server.key' }}
        pgsql_log_to_csvlog: true
        pgsql_log_to_syslog: true
        pgsql_vault_ssl_mode: verify-full
        pgsql_vault_access_hostname: "{{ hostvars['linux'].ansible_fqdn }}"
        pgsql_vault_database_mount_point: database
        pgsql_vault_monitor_mount_point: monitoring
        pgsql_vault_ip_addresses:
          - "{{ hostvars['vault'].ansible_host }}"
  playbooks:
    verify: ../common/verify/main.yml
verifier:
  name: ansible
